version: '3.8'
services:
  db:
    image: postgres:15
    container_name: patri-hub-db
    environment:
      POSTGRES_DB: patrihub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: patrihub123
    ports:
      - "5433:5432"
    volumes:
      - patrihub-data:/var/lib/postgresql/data

volumes:
  patrihub-data:
